# permissions for end users to edit configsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configset-editor-role
rules:
  - apiGroups:
      - common.nodemanager
    resources:
      - configsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - common.nodemanager
    resources:
      - configsets/status
    verbs:
      - get
