# permissions for end users to view configsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configset-viewer-role
rules:
  - apiGroups:
      - common.nodemanager
    resources:
      - configsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - common.nodemanager
    resources:
      - configsets/status
    verbs:
      - get
