# permissions for end users to view managednodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managednode-viewer-role
rules:
  - apiGroups:
      - common.nodemanager
    resources:
      - managednodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - common.nodemanager
    resources:
      - managednodes/status
    verbs:
      - get
